### ISSUE TITLE
Cannot POST axios for login

### ISSUE THREAD

**Issue by TauqeerAhmad5201** [TauqeerAhmad5201/fullstack-demo#4]
Checkout my code for login. 
Cannot POST / 
[index.js](https://github.com/TauqeerAhmad5201/fullstack-demo/blob/main/backend/index.js#L26)

Screenshot: 
![404](https://user-images.githubusercontent.com/68806440/236672674-7fa4d63f-2c54-4b8b-a3ef-7500cf1d136c.png)

**Comment by adnanhashmi09** [comment]
remove `action="#"` in form inside login.js. Remove `method="POST"` as well. 

then handle the submit using 
```js
<form onSubmit={handleSubmit}>
      {...........}
<form>
```

**Comment by TauqeerAhmad5201** [comment]
Solved using restarting the port.
